apiVersion: v1
kind: Service

metadata:
  name: dockflex-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  selector:
    app: dockflex

  type: LoadBalancer

  ports:
  - protocol: TCP
    port: 80
    targetPort: 7000
